# Generated by Django 4.0.6 on 2022-07-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=64, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=32, verbose_name='用户登录名')),
                ('user_pwd', models.CharField(max_length=64, verbose_name='用户密码')),
                ('user_state', models.SmallIntegerField(choices=[(1, '启用'), (2, '禁用')], verbose_name='帐号状态')),
            ],
        ),
    ]
